### PR TITLE
Feature#31 crud appointments

### LINKED ISSUE #31: Create CRUD Appointments
# REQUIREMENTS
Create the functionality to make appointments

# Acceptance Criteria
List all required acceptance criteria
- [x] Patient should  be a valid-user
- [x] psychologist should be a valid-user
- [x] It should have a valid date
- [x] Make the relationship between patient and psychologist

### PR DESCRIPTION
**Pull request by xFerchoVJ**
# Description
What did you implemented/Why did you implemented this:
 - We've created the crud for appointments
 - Made the backend for patients and psychologist for the appointments
 
Resolve #31

### CODE REVIEW

**Review by oramasangel — DISMISSED** [review]
lgtm

**Review by brayandiazc — APPROVED** [review]

**Review by OmarRoBra — APPROVED** [review]
Add some spaces in the views, and what a nice job :D

**Review by martinmt-mx — APPROVED** [review]
nice!

**Review by OmarRoBra — APPROVED** [review]

**Review by RobertoCarMed — APPROVED** [review]
LGTM!

**Pull request merged**
